config/routes.rb
Personal::Application.routes.draw do
  get "static_pages/becoming_wikipedian"
  get "static_pages/social_security_sensitivity_slides"

  get "home/index"
  get "home/about"

  get "search/index"
  post "search/index"

  post "cv_download_count/increment", as: 'cv'

  resources :updates

  resources :papers do
    collection do
      get 'serve'
    end
  end

  resources :collaborators

  resources :essays

  resources :projects do
    collection do
      get 'list'
    end
  end

  root :to => "home#index"
  match "about" => "home#about"

end

app/models/collaborator.rb
class Collaborator < ActiveRecord::Base
  has_and_belongs_to_many :projects
  has_and_belongs_to_many :essays
  has_and_belongs_to_many :papers

  def full_name
    "#{first_name} #{last_name}"
  end

  def full_name=(name)
    first_name,last_name = name.split(' ')
  end

  def name_auth
    "#{last_name}, #{first_name[0]}."
  end

  def as_json(options={})
    {
      id: self.id,
      name: self.full_name
    }
  end
end
# == Schema Information
#
# Table name: collaborators
#
#  id         :integer         not null, primary key
#  first_name :string(255)
#  last_name  :string(255)
#  website    :string(255)
#  email      :string(255)
#  created_at :datetime
#  updated_at :datetime
#

app/controllers/collaborators_controller.rb
class CollaboratorsController < ApplicationController
  before_filter :authenticate, :except => [:index,:show]
  # GET /collaborators
  # GET /collaborators.json
  def index
    @collaborators = (params[:q] ? Collaborator.where("(first_name like :q) or (last_name like :q)",{:q => "%#{params[:q]}%"}): Collaborator.all.sort {|a,b| a.last_name <=> b.last_name})

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @collaborators }
    end
  end

  # GET /collaborators/1
  # GET /collaborators/1.json
  def show
    @collaborator = Collaborator.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @collaborator }
    end
  end

  # GET /collaborators/new
  # GET /collaborators/new.json
  def new
    @collaborator = Collaborator.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @collaborator }
    end
  end

  # GET /collaborators/1/edit
  def edit
    @collaborator = Collaborator.find(params[:id])
  end

  # POST /collaborators
  # POST /collaborators.json
  def create
    @collaborator = Collaborator.new(params[:collaborator])

    respond_to do |format|
      if @collaborator.save
        format.html { redirect_to @collaborator, notice: 'Collaborator was successfully created.' }
        format.json { render json: @collaborator, status: :created, location: @collaborator }
      else
        format.html { render action: "new" }
        format.json { render json: @collaborator.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /collaborators/1
  # PUT /collaborators/1.json
  def update
    @collaborator = Collaborator.find(params[:id])

    respond_to do |format|
      if @collaborator.update_attributes(params[:collaborator])
        format.html { redirect_to @collaborator, notice: 'Collaborator was successfully updated.' }
        format.json { head :ok }
      else
        format.html { render action: "edit" }
        format.json { render json: @collaborator.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /collaborators/1
  # DELETE /collaborators/1.json
  def destroy
    @collaborator = Collaborator.find(params[:id])
    @collaborator.destroy

    respond_to do |format|
      format.html { redirect_to collaborators_url }
      format.json { head :ok }
    end
  end


  protected

  def authenticate
    authenticate_or_request_with_http_basic do |user, password|
      retval = user == 'ced' && password == 'carver'
      session[:authenticated] = true if retval
      retval
    end
  end
end

app/helpers/collaborators_helper.rb
module CollaboratorsHelper
end

app/views/collaborators/_form.html.haml
= form_for @collaborator, :html => { :class => 'form-horizontal' } do |f|
  %fieldset
    %legend
      = controller.action_name.capitalize
      \/Collaborator
    .control-group
      = f.label :first_name, :class => 'control-label'
      .controls
        = f.text_field :first_name, :class => 'text_field'
    .control-group
      = f.label :last_name, :class => 'control-label'
      .controls
        = f.text_field :last_name, :class => 'text_field'
    .control-group
      = f.label :website, :class => 'control-label'
      .controls
        = f.text_field :website, :class => 'text_field'
    .control-group
      = f.label :email, :class => 'control-label'
      .controls
        = f.text_field :email, :class => 'text_field'
    .form-actions
      = f.submit nil, :class => 'btn btn-primary'
      = link_to 'Cancel', collaborators_path, :class => 'btn'

app/views/collaborators/index.html.haml
%table.table.table-striped
  %thead
    %tr
      %th Name
      %th Projects collaboratored on
      %th Essays coauthored
      %th Papers coauthored
  %tbody
    - @collaborators.sort { |a,b| b.papers.length <=> a.papers.length }.each do |collaborator|
      %tr
        %td= link_to collaborator.full_name, collaborator_path(collaborator)
        %td= collaborator.projects.length
        %td= collaborator.essays.length
        %td= collaborator.papers.length
- if session[:authenticated]
  = link_to 'New', new_collaborator_path, :class => 'btn btn-primary pull-right'

app/views/collaborators/show.html.haml
%h2.header= @collaborator.full_name
%p.header
  = link_to 'Website', (@collaborator.website[0..6] == 'http://' ? @collaborator.website : "http://#{@collaborator.website}")
  | #{mail_to @collaborator.email, 'E-mail'}
- active = (@collaborator.projects.length > 0 ? 'projects' : ( @collaborator.essays.length > 0 ? 'essays' : ( @collaborator.papers.length > 0 ? 'papers' : 'nothing' ) ) )
%ul.nav.nav-tabs
  = "<li #{(active == 'projects' ? 'class="active"' : '')}><a href=\"#projects\" data-toggle=\"tab\">Projects</a></li>".html_safe if @collaborator.projects.length > 0
  = "<li #{(active == 'essays' ? 'class="active"' : '')}><a href=\"#essays\" data-toggle=\"tab\">Essays</a></li>".html_safe if @collaborator.essays.length > 0
  = "<li  #{(active == 'papers' ? 'class="active"' : '')}><a href=\"#papers\" data-toggle=\"tab\">Papers</a></li>".html_safe if @collaborator.papers.length > 0
- active = true
.tab-content
  - if @collaborator.projects.length > 0
    - active = false
    #projects.tab-pane.active
      %h3 Projects
      - @collaborator.projects.each do |project|
        .row
          .span2.well.projitem.header
            = image_tag(project.preview.url(:projthumb))
          .span9.well.projitem
            %h3.bottom-marg= project.title
            %p= project.description
            %p.tags
              %strong Tags:
              - project.tags.each do |tag|
                = link_to tag, {:controller => :search, :action => :index, :tags => tag}, html_options = {:class => "label" }
            %p
              %a.btn.pull-right{:href => project_path(project)} View more &raquo;
  - if @collaborator.essays.length > 0
    #essays{:class => "tab-pane #{active ? 'active' : ''}"}
      - active = false
      %h3 Essays
      %table.table.table-striped
        %thead
          %tr
            %th Title
            %th Description
            %th Created
            %th Updated
        %tbody
          - @collaborator.essays.each do |essay|
            %tr
              %td= link_to essay.title, essay_path(essay)
              %td= essay.description
              %td= essay.created_at.strftime("%m/%d/%Y")
              %td= essay.updated_at.strftime("%m/%d/%Y")
              %td
  - if @collaborator.papers.length > 0
    #papers{:class => "tab-pane #{active ? 'active' : ''}"}
      - active = false
      %h3 Papers
      %table.table.table-striped
        %tbody
          - @collaborator.papers.each do |paper|
            %tr
              %td{:width => "95%"}
                - if paper.citation and not paper.citation == ""
                  = paper.citation
                - else
                  = link_to 'Das, S.', root_path, :class => 'author' if paper.collaborators.length == 0
                  - paper.collaborators.each.each_with_index do |collab,i|
                    = link_to (i == paper.collaborators.length - 1 ? 'Das, S.,' : 'Das,S.'), root_path, :class => 'author' if i+1 == paper.self_author_order
                    = link_to (i == paper.collaborators.length - 1 ? collab.name_auth : "#{collab.name_auth},"), collaborator_path(collab), :class => 'author'
                  %span.title= paper.title
                  %span.venue= paper.venue
                  = succeed "." do
                    %span.year= paper.year
                  = "<span class=\"volume\">#{paper.volume}</span>".html_safe if paper.volume
                  = "<span class=\"issue\">(#{paper.issue})</span>.".html_safe if paper.issue
                  = "<span class=\"page_nums\">pp #{paper.page_nums}</span>".html_safe if paper.page_nums
                  [
                  %span.acc-rate>= paper.accept_rate
                  \% accept rate]
              %td= link_to 'PDF', paper.pdf.url
:javascript
  $(function () {
      $('.tabs a:last').tab('show')
    })
- if session[:authenticated]
  .form-actions
    = link_to 'Back', collaborators_path, :class => 'btn'
    = link_to 'Edit', edit_collaborator_path(@collaborator), :class => 'btn'
    = link_to 'Delete', collaborator_path(@collaborator), :method => 'delete', :confirm => 'Are you sure?', :class => 'btn btn-danger'