config/routes.rb
Personal::Application.routes.draw do
  get "static_pages/becoming_wikipedian"
  get "static_pages/social_security_sensitivity_slides"

  get "home/index"
  get "home/about"

  get "search/index"
  post "search/index"

  post "cv_download_count/increment", as: 'cv'

  resources :updates

  resources :papers do
    collection do
      get 'serve'
    end
  end

  resources :collaborators

  resources :essays

  resources :projects do
    collection do
      get 'list'
    end
  end

  root :to => "home#index"
  match "about" => "home#about"

end

app/models/project.rb
class Project < ActiveRecord::Base
  has_attached_file :featured,
    :styles => {
      :full => "940x300#"
    }

  has_attached_file :preview,
    :styles => {
      :mglarge => "320x240#",
      :projthumb => "180x180#",
      :mgsmall => "260x180#" }
    #:storage => :s3,
    #:bucket => 'tw_bucket',
    #:s3_credentials => {
    #  :access_key_id => ENV['S3_KEY'],
    #  :secret_access_key => ENV['S3_SECRET']
    #}

  validates_attachment_content_type :featured, :content_type => ['image/jpeg', 'image/png', 'image/bmp', 'image/gif']
  validates_attachment_content_type :preview, :content_type => ['image/jpeg', 'image/png', 'image/bmp', 'image/gif']
  has_and_belongs_to_many :collaborators
  serialize :tags,Array 
  attr_reader :tokenCollabList
  #attr_accessible :tokenCollabList


  def has_tag?(tag)
    self.tags.include?(tag)
  end

  def tokenCollabList=(list)
    self.collaborator_ids = list.split(",")
  end

  def taglist
    self.tags.join(',')
  end

  def taglist=(list)
    self.tags = list.split(',').map { |t| t.strip }
    self.save
  end
end
# == Schema Information
#
# Table name: projects
#
#  id                    :integer         not null, primary key
#  tags                  :text
#  markup                :text
#  description           :string(255)
#  created_at            :datetime
#  updated_at            :datetime
#  featured_file_name    :string(255)
#  featured_content_type :string(255)
#  featured_file_size    :integer
#  featured_updated_at   :datetime
#  preview_file_name     :string(255)
#  preview_content_type  :string(255)
#  preview_file_size     :integer
#  preview_updated_at    :datetime
#  title                 :string(255)
#  is_featured           :boolean
#

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
  before_filter :authenticate, :except => [:index,:show,:list]

  # GET /projects
  # GET /projects.json
  def index
    @featured = Project.find_all_by_is_featured(true)
    others = Project.order("created_at").select { |proj| not proj.is_featured }.first(11).reverse
    if others.length > 3
      @subfeatured,@mediagrid = [others.first(3),others.last(others.length-3)]
    else
      @subfeatured = others
    end

    @essays = Essay.order("created_at").first(6).reverse
  end

  def list
    @projects = Project.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @projects }
    end
  end

  # GET /projects/1
  # GET /projects/1.json
  def show
    @project = Project.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @project }
    end
  end

  # GET /projects/new
  # GET /projects/new.json
  def new
    @project = Project.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @project }
    end
  end

  # GET /projects/1/edit
  def edit
    @project = Project.find(params[:id])
  end

  def updateCollaborators(project,collabslist)
    project.collaborators = []
    collabslist.each do |collab|
      collaborator = Collaborator.find_by_id(collab)
      if collaborator
        collaborator.projects << project if not collaborator.projects.include?(project)
      end
    end
    project.save
  end

  # POST /projects
  # POST /projects.json
  def create
    collabParam = params[:project][:collaborators]
    @project = Project.new(params[:project])

    respond_to do |format|
      if @project.save
        format.html { redirect_to @project, notice: 'Project was successfully created.' }
        format.json { render json: @project, status: :created, location: @project }
      else
        format.html { render action: "new" }
        format.json { render json: @project.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /projects/1
  # PUT /projects/1.json
  def update
    @project = Project.find(params[:id])
    puts "Printed Tags Are: #{params[:project][:taglist]}" 

    respond_to do |format|
      if @project.update_attributes(params[:project])
        format.html { redirect_to @project, notice: 'Project was successfully updated.' }
        format.json { head :ok }
      else
        format.html { render action: "edit" }
        format.json { render json: @project.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /projects/1
  # DELETE /projects/1.json
  def destroy
    @project = Project.find(params[:id])
    @project.destroy

    respond_to do |format|
      format.html { redirect_to projects_url }
      format.json { head :ok }
    end
  end

  protected

  def authenticate
    authenticate_or_request_with_http_basic do |user, password|
      retval = user == 'ced' && password == 'carver'
      session[:authenticated] = true if retval
      retval
    end
  end
end

app/helpers/projects_helper.rb
module ProjectsHelper
end

app/views/projects/_form.html.haml
= form_for @project, :html => { :class => 'form-horizontal' } do |f|
  %fieldset
    %legend
      = controller.action_name.capitalize
      \/Project
    .control-group
      = f.label :title, :class => 'control-label'
      .controls
        = f.text_field :title, :class => 'text_field'
    .control-group
      = f.label :tokenCollabList, 'Collaborators', :class => 'control-label'
      .controls{:style => "float:left;margin-left:20px;"}
        = f.text_field :tokenCollabList, :placeholder => 'Separate collaborators with commas', "data-pre" => @project.collaborators.to_json
    .control-group
      = f.label :description, :class => 'control-label'
      .controls
        = f.text_area :description, :class => 'text_field', :size => '20x10'
    .control-group
      = f.label :markup, :class => 'control-label'
      .controls
        = f.cktext_area :markup, :toolbar=>'Full', :width=>'750px', :height=>'600px'
    .control-group
      = f.label :taglist, 'Tags:', :class => 'control-label'
      .controls
        = f.text_field :taglist, :placeholder => 'Separate tags with commas'
    .control-group
      = f.label :featured, 'Featured Photo:', :class => 'control-label'
      .controls
        = f.file_field :featured, :class => 'file_field'
    .control-group
      = f.label :preview, 'Preview Photo:', :class => 'control-label'
      .controls
        = f.file_field :preview, :class => 'file_field'
    .control-group
      = f.label :is_featured, :class => 'control-label'
      .controls
        = f.check_box :is_featured, :class => 'check_box'
    .form-actions
      = f.submit nil, :class => 'btn btn-primary'
      = link_to 'Cancel', projects_path, :class => 'btn'
:javascript
  $(function() {
    $("#project_tokenCollabList").tokenInput("/collaborators.json", {
      crossDomain: false,
      prePopulate: $("#project_tokenCollabList").data("pre"),
      theme: "facebook"
    });
  });

app/views/projects/index.html.haml
.actions
  = link_to 'List All Projects', '/projects/list'
- if @featured
  %h1.bottom-marg Featured Projects
  #myCarousel.carousel
    / Carousel items
    .carousel-inner
      - @featured.each do |feat|
        %div{:class => "item carousel-item#{' active' if feat == @featured.first}"}
          %img{:src => feat.featured.url(:full)}/
          .carousel-caption.bottom-marg
            %h4= feat.title
            %p= link_to "Learn more", project_path(feat), :class => "btn btn-primary btn-large pull-right bottom-marg"
    / Carousel nav
    %a.carousel-control.left{"data-slide" => "prev", :href => "#myCarousel"} &lsaquo;
    %a.carousel-control.right{"data-slide" => "next", :href => "#myCarousel"} &rsaquo;
- if @subfeatured
  %h1.bottom-marg Other Recent Projects
  .row
    - @subfeatured.each do |subfeat|
      .span4_bordered.bordered.clickable_proj{id: subfeat.id}
        %div
          %h3.heading
            = link_to subfeat.title, project_path(subfeat)
        .thumbmg.center
          = image_tag (subfeat.preview.exists? ? subfeat.preview.url(:projthumb) : 'http://placehold.it/180x180')
        %hr/
        %p= subfeat.description[0..150] + ( subfeat.description.length > 150 ? '...' : '' )
        %hr/
        %p.tags
          %strong Tags:
          - subfeat.tags.each do |tag|
            = link_to tag, {:controller => :search, :action => :index, :tags => tag}, html_options = {:class => "label" }
- if @mediagrid
  %h2 Other Work
  %ul.thumbnails
    - @mediagrid.first(3).each do |mgobj|
      %li.span4= link_to image_tag((mgobj.preview.exists? ? mgobj.preview.url(:mglarge) : 'http://placehold.it/320x240')), project_path(mgobj)
    - if @mediagrid.length > 3
      - @mediagrid.last(@mediagrid.length - 3).each do |mgobj|
        %li.span3= link_to image_tag((mgobj.preview.exists? ? mgobj.preview.url(:mgsmall) : 'http://placehold.it/260x180')), project_path(mgobj)

app/views/projects/list.html.haml
- @projects.each do |project|
  .row.clickable_proj{id: project.id}
    .span2.well.projitem.header
      = image_tag(project.preview.url(:projthumb))
    .span9.well.projitem
      %h3.bottom-marg= project.title
      %p= project.description
      %p.tags
        %strong Tags:
        - project.tags.each do |tag|
          = link_to tag, {:controller => :search, :action => :index, :tags => tag}, html_options = {:class => "label" }
      %p
        %a.btn.pull-right{:href => project_path(project)} View more &raquo;
- if session[:authenticated]
  = link_to 'New', new_project_path, :class => 'btn btn-primary pull-right'

app/views/projects/show.html.haml
%h1.header.bottom-marg= @project.title
.featured_img.field.bottom-marg
  - if @project.featured.exists?
    = link_to image_tag(@project.featured.url(:full)), @project.featured.url, :class=>'feat_img'
%p
  %b Collaborators:
  = @project.collaborators.map { |collab| link_to collab.full_name, collaborator_path(collab), :class => 'collab' }.join(',').html_safe
%p.bottom-marg
  %b Tags:
  = @project.tags.map { |tag| link_to tag, {:controller => :search, :action => :index, :tags => tag}, html_options = {:class => "label" }}.join(' ').html_safe
%hr/
.row
  .well{:style => "width:940px;"}= @project.markup.html_safe
- if session[:authenticated]
  .form-actions
    = link_to 'Back', projects_path, :class => 'btn'
    = link_to 'Edit', edit_project_path(@project), :class => 'btn'
    = link_to 'Delete', project_path(@project), :method => 'delete', :confirm => 'Are you sure?', :class => 'btn btn-danger'