config/routes.rb
Personal::Application.routes.draw do
  get "static_pages/becoming_wikipedian"
  get "static_pages/social_security_sensitivity_slides"

  get "home/index"
  get "home/about"

  get "search/index"
  post "search/index"

  post "cv_download_count/increment", as: 'cv'

  resources :updates

  resources :papers do
    collection do
      get 'serve'
    end
  end

  resources :collaborators

  resources :essays

  resources :projects do
    collection do
      get 'list'
    end
  end

  root :to => "home#index"
  match "about" => "home#about"

end

app/models/paper.rb
class Paper < ActiveRecord::Base
  has_attached_file :pdf
  has_and_belongs_to_many :collaborators

  validates_attachment_content_type :pdf, :content_type => ['application/pdf', 'application/msword', 'text/plain']
  attr_reader :tokenCollabList

  def tokenCollabList=(list)
    self.collaborator_ids = list.split(",")
  end

  def self.conference_papers
    Paper.all.select do |paper|
      paper.papertype == "1"
    end
  end

  def self.journal_papers
    Paper.all.select do |paper|
      paper.papertype == "2"
    end
  end

  def self.workshop_papers
    Paper.all.select do |paper|
      paper.papertype == "3"
    end
  end

  def safe_downloads
    self.downloads || 0
  end
end
# == Schema Information
#
# Table name: papers
#
#  id                :integer         not null, primary key
#  citation          :string(255)
#  created_at        :datetime
#  updated_at        :datetime
#  pdf_file_name     :string(255)
#  pdf_content_type  :string(255)
#  pdf_file_size     :integer
#  pdf_updated_at    :datetime
#  year              :integer
#  venue             :string(255)
#  accept_rate       :float
#  title             :string(255)
#  self_author_order :integer
#  volume            :integer
#  issue             :integer
#  page_nums         :string(255)
#  papertype         :string(255)
#  downloads         :integer
#

app/controllers/papers_controller.rb
class PapersController < ApplicationController
  before_filter :authenticate, :except => [:index,:show,:serve]

  # GET /papers
  # GET /papers.json
  def index
    @papers = Paper.all.reverse

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @papers }
    end
  end

  # GET /papers/1
  # GET /papers/1.json
  #def show
  #  @paper = Paper.find(params[:id])
  #
  #  respond_to do |format|
  #    format.html # show.html.erb
  #    format.json { render json: @paper }
  #  end
  #end

  # GET /papers/new
  # GET /papers/new.json
  def new
    @paper = Paper.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @paper }
    end
  end

  # GET /papers/1/edit
  def edit
    @paper = Paper.find(params[:id])
  end

  # POST /papers
  # POST /papers.json
  def create
    @paper = Paper.new(params[:paper])

    respond_to do |format|
      if @paper.save
        format.html { redirect_to @paper, notice: 'Paper was successfully created.' }
        format.json { render json: @paper, status: :created, location: @paper }
      else
        format.html { render action: "new" }
        format.json { render json: @paper.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /papers/1
  # PUT /papers/1.json
  def update
    @paper = Paper.find(params[:id])

    respond_to do |format|
      if @paper.update_attributes(params[:paper])
        format.html { redirect_to papers_path, notice: 'Paper was successfully updated.' }
        format.json { head :ok }
      else
        format.html { render action: "edit" }
        format.json { render json: @paper.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /papers/1
  # DELETE /papers/1.json
  def destroy
    @paper = Paper.find(params[:id])
    @paper.destroy

    respond_to do |format|
      format.html { redirect_to papers_url }
      format.json { head :ok }
    end
  end

  def serve
    @paper = Paper.find(params[:id])
    @paper.downloads = @paper.downloads ? @paper.downloads + 1 : 1
    @paper.save

    redirect_to @paper.pdf.url
  end

  protected

  def authenticate
    authenticate_or_request_with_http_basic do |user, password|
      retval = user == 'ced' && password == 'carver'
      session[:authenticated] = true if retval
      retval
    end
  end
end

app/helpers/papers_helper.rb
module PapersHelper
end

app/views/papers/_form.html.haml
= form_for @paper, :html => { :class => 'form-horizontal' } do |f|
  %fieldset
    %legend
      = controller.action_name.capitalize
      \/Paper
    .control-group
      = f.label :title, :class => 'control-label'
      .controls
        = f.text_field :title, :class => 'text_field'
    .control-group
      = f.label :tokenCollabList, 'Collaborators', :class => 'control-label'
      .controls{:style => "float:left;margin-left:20px;"}
        = f.text_field :tokenCollabList, :placeholder => 'Separate collaborators with commas', "data-pre" => @paper.collaborators.to_json
    .control-group
      = f.label :year, :class => 'control-label'
      .controls
        = f.number_field :year, :class => 'number_field'
    .control-group
      = f.label :venue, :class => 'control-label'
      .controls
        = f.text_field :venue, :class => 'text_field'
    .control-group
      = f.label :accept_rate, :class => 'control-label'
      .controls
        = f.text_field :accept_rate, :class => 'text_field'
    .control-group
      = f.label :self_author_order, :class => 'control-label'
      .controls
        = f.text_field :self_author_order, :class => 'text_field'
    .control-group
      = f.label :volume, :class => 'control-label'
      .controls
        = f.number_field :volume, :class => 'number_field'
    .control-group
      = f.label :issue, :class => 'control-label'
      .controls
        = f.number_field :issue, :class => 'number_field'
    .control-group
      = f.label :page_nums, :class => 'control-label'
      .controls
        = f.text_field :page_nums, :class => 'text_field'
    .control-group
      = f.label :papertype, :class => 'control-label'
      .controls
        = f.select :papertype,  { :Conference => "1", :Journal => "2", :Workshop => "3"}, html_options = {:class => 'text_field'}
    .control-group
      = f.label :citation, :class => 'control-label'
      .controls
        = f.text_field :citation, :class => 'text_field'
    .control-group
      = f.label :pdf, :class => 'control-label'
      .controls
        = f.file_field :pdf, :class => 'file_field'
    .form-actions
      = f.submit nil, :class => 'btn btn-primary'
      = link_to 'Cancel', papers_path, :class => 'btn'
:javascript
  $(function() {
    $("#paper_tokenCollabList").tokenInput("/collaborators.json", {
      crossDomain: false,
      prePopulate: $("#paper_tokenCollabList").data("pre"),
      theme: "facebook"
    });
  });

app/views/papers/_paper.html.haml
.row.pubdiv
  .span11
    %p{align: "left"}
      = link_to 'Das, S.', root_path, :class => 'author' if paper.collaborators.length == 0
      - paper.collaborators.each.each_with_index do |collab,i|
        = link_to (i == paper.collaborators.length - 1 ? 'Das, S.,' : 'Das,S.'), root_path, class: 'author' if i+1 == paper.self_author_order
        = link_to (i == paper.collaborators.length - 1 ? collab.name_auth : "#{collab.name_auth},"), collaborator_path(collab), class: 'author'
      = succeed "." do
        %span.title= paper.title
      %span.venue= paper.venue
      = succeed "." do
        %span.year= paper.year
      = "<span class=\"volume\">#{paper.volume}</span>".html_safe if paper.volume
      = "<span class=\"issue\">(#{paper.issue})</span>.".html_safe if paper.issue
      = "<span class=\"page_nums\">pp #{paper.page_nums}</span>".html_safe if paper.page_nums and paper.page_nums != ""
      = "[<span class=\"acc-rate\">#{paper.accept_rate}</span>% accept rate]".html_safe if paper.accept_rate and paper.accept_rate != ""
  .span1
    = link_to 'PDF', controller: :papers, action: :serve, id: paper.id

app/views/papers/_paper_table.html.haml
%tr
  %td{:width => "90%"}
    = link_to 'Das, S.', root_path, :class => 'author' if paper.collaborators.length == 0
    - paper.collaborators.each.each_with_index do |collab,i|
      = link_to (i == paper.collaborators.length - 1 ? 'Das, S.,' : 'Das,S.'), root_path, :class => 'author' if i+1 == paper.self_author_order
      = link_to (i == paper.collaborators.length - 1 ? collab.name_auth : "#{collab.name_auth},"), collaborator_path(collab), :class => 'author'
    = succeed "." do
      %span.title= paper.title
    %span.venue= paper.venue
    = succeed "." do
      %span.year= paper.year
    = "<span class=\"volume\">#{paper.volume}</span>".html_safe if paper.volume
    = "<span class=\"issue\">(#{paper.issue})</span>.".html_safe if paper.issue
    = "<span class=\"page_nums\">pp #{paper.page_nums}</span>".html_safe if paper.page_nums and paper.page_nums != ""
    = "[<span class=\"acc-rate\">#{paper.accept_rate}</span>% accept rate]".html_safe if paper.accept_rate and paper.accept_rate != ""
  %td
    = link_to 'PDF', controller: :papers, action: :serve, id: paper.id
  %td
    = paper.downloads

app/views/papers/index.html.haml
- conference_papers = @papers.select { |paper| paper.papertype == "1" }
- journal_papers = @papers.select { |paper| paper.papertype == "2" }
- workshop_papers = @papers.select { |paper| paper.papertype == "3" }
- if journal_papers.length > 0
  %h2 Journal Papers
  %table.table.table-striped
    %tbody
      = render partial: 'paper_table', collection: journal_papers, as: :paper
- if conference_papers.length > 0
  %h2 Conference Papers
  %table.table.table-striped
    %tbody
      = render partial: 'paper_table', collection: conference_papers, as: :paper
- if workshop_papers.length > 0
  %h2 Workshop Papers
  %table.table.table-striped
    %tbody
      = render partial: 'paper_table', collection: workshop_papers, as: :paper

app/views/papers/show.html.haml
%h1 /Paper
%p
  %b Citation
  %br/
  = @paper.citation if paper.citation
%p
  %b Pdf file name
  %br/
  = @paper.pdf_file_name
%p
  %b Pdf content type
  %br/
  = @paper.pdf_content_type
%p
  %b Pdf file size
  %br/
  = @paper.pdf_file_size
%p
  %b Pdf updated at
  %br/
  = @paper.pdf_updated_at
%p
  %b Year
  %br/
  = @paper.year
%p
  %b Venue
  %br/
  = @paper.venue
%p
  %b Accept rate
  %br/
  = @paper.accept_rate
%p
  %b Title
  %br/
  = @paper.title
- if session[:authenticated]
  .form-actions
    = link_to 'Back', papers_path, :class => 'btn'
    = link_to 'Edit', edit_paper_path(@paper), :class => 'btn'
    = link_to 'Delete', paper_path(@paper), :method => 'delete', :confirm => 'Are you sure?', :class => 'btn btn-danger'