config/routes.rb
Personal::Application.routes.draw do
  get "static_pages/becoming_wikipedian"
  get "static_pages/social_security_sensitivity_slides"

  get "home/index"
  get "home/about"

  get "search/index"
  post "search/index"

  post "cv_download_count/increment", as: 'cv'

  resources :updates

  resources :papers do
    collection do
      get 'serve'
    end
  end

  resources :collaborators

  resources :essays

  resources :projects do
    collection do
      get 'list'
    end
  end

  root :to => "home#index"
  match "about" => "home#about"

end

app/models/essay.rb
class Essay < ActiveRecord::Base
  has_and_belongs_to_many :collaborators
  serialize :tags, Array
  attr_reader :tokenCollabList

  def tokenCollabList=(list)
    self.collaborator_ids = list.split(",")
  end

  def taglist
    self.tags.join(',')
  end

  def taglist=(list)
    self.tags = list.split(',').map { |t| t.strip }
    self.save
  end
end
# == Schema Information
#
# Table name: essays
#
#  id          :integer         not null, primary key
#  description :string(255)
#  tags        :text
#  markup      :text
#  created_at  :datetime
#  updated_at  :datetime
#  title       :string(255)
#

app/controllers/essays_controller.rb
class EssaysController < ApplicationController
  before_filter :authenticate, :except => [:index,:show]
  # GET /essays
  # GET /essays.json
  def index
    @essays = Essay.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @essays }
    end
  end

  # GET /essays/1
  # GET /essays/1.json
  def show
    @essay = Essay.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @essay }
    end
  end

  # GET /essays/new
  # GET /essays/new.json
  def new
    @essay = Essay.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @essay }
    end
  end

  # GET /essays/1/edit
  def edit
    @essay = Essay.find(params[:id])
  end

  # POST /essays
  # POST /essays.json
  def create
    @essay = Essay.new(params[:essay])

    respond_to do |format|
      if @essay.save
        format.html { redirect_to @essay, notice: 'Essay was successfully created.' }
        format.json { render json: @essay, status: :created, location: @essay }
      else
        format.html { render action: "new" }
        format.json { render json: @essay.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /essays/1
  # PUT /essays/1.json
  def update
    @essay = Essay.find(params[:id])

    respond_to do |format|
      if @essay.update_attributes(params[:essay])
        format.html { redirect_to @essay, notice: 'Essay was successfully updated.' }
        format.json { head :ok }
      else
        format.html { render action: "edit" }
        format.json { render json: @essay.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /essays/1
  # DELETE /essays/1.json
  def destroy
    @essay = Essay.find(params[:id])
    @essay.destroy

    respond_to do |format|
      format.html { redirect_to essays_url }
      format.json { head :ok }
    end
  end


  protected

  def authenticate
    authenticate_or_request_with_http_basic do |user, password|
      retval = user == 'ced' && password == 'carver'
      session[:authenticated] = true if retval
      retval
    end
  end
end

app/helpers/essays_helper.rb
module EssaysHelper
end

app/views/essays/_form.html.haml
= form_for @essay, :html => { :class => 'form-horizontal' } do |f|
  %fieldset
    %legend
      = controller.action_name.capitalize
      \/Essay
    .control-group
      = f.label :title, :class => 'control-label'
      .controls
        = f.text_field :title, :class => 'text_field'
    .control-group
      = f.label :tokenCollabList, 'Co-Authors', :class => 'control-label'
      .controls{:style => "float:left;margin-left:20px;"}
        = f.text_field :tokenCollabList, :placeholder => 'Separate collaborators with commas', "data-pre" => @essay.collaborators.to_json
    .control-group
      = f.label :taglist, 'Tags:', :class => 'control-label'
      .controls
        = f.text_field :taglist, :placeholder => 'Separate tags with commas'
    .control-group
      = f.label :description, :class => 'control-label'
      .controls
        = f.text_area :description, :class => 'text_field', :size => '20x10'
    .control-group
      = f.label :markup, :class => 'control-label'
      .controls
        = f.cktext_area :markup, :toolbar=>'Full', :width=>'750px', :height=>'600px'
    .form-actions
      = f.submit nil, :class => 'btn btn-primary'
      = link_to 'Cancel', essays_path, :class => 'btn'
:javascript
  $(function() {
    $("#essay_tokenCollabList").tokenInput("/collaborators.json", {
      crossDomain: false,
      prePopulate: $("#essay_tokenCollabList").data("pre"),
      theme: "facebook"
    });
  });

app/views/essays/index.html.haml
%table.table.table-striped
  %thead
    %tr
      %th Title
      %th Description
      %th Created
      %th Updated
  %tbody
    - @essays.each do |essay|
      %tr
        %td= link_to essay.title, essay_path(essay)
        %td= essay.description
        %td= essay.created_at.strftime("%m/%d/%Y")
        %td= essay.updated_at.strftime("%m/%d/%Y")
        %td
- if session[:authenticated]
  = link_to 'New', new_essay_path, :class => 'btn btn-primary pull-right'

app/views/essays/show.html.haml
%h1.header= @essay.title
%p.header
  = link_to 'Sauvik Das', root_path
  - @essay.collaborators.each do |collab|
    ,   #{link_to collab.full_name, collaborator_path(collab)}
%p.header.description
  = @essay.description
%hr/
.row
  .well{:style => "width:940px;"}= @essay.markup.html_safe
%p
  %b Tags:
  = @essay.tags.map { |tag| link_to tag, {:controller => :search, :action => :index, :tags => tag}, html_options = {:class => "label" }}.join(',').html_safe
- if session[:authenticated]
  .form-actions
    = link_to 'Back', essays_path, :class => 'btn'
    = link_to 'Edit', edit_essay_path(@essay), :class => 'btn'
    = link_to 'Delete', essay_path(@essay), :method => 'delete', :confirm => 'Are you sure?', :class => 'btn btn-danger'